import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/db'
import { scans, fileReviews, repositories } from '@/db/schema'
import { eq } from 'drizzle-orm'

export async function GET(
    _req: NextRequest,
    { params }: { params: { scanId: string } }
) {
    const scanId = parseInt(params.scanId)
    const scan = await db.query.scans.findFirst({ where: eq(scans.id, scanId) })
    if (!scan) return NextResponse.json({ error: 'Scan not found' }, { status: 404 })

    const reviews = await db.query.fileReviews.findMany({ where: eq(fileReviews.scanId, scanId) })
    const repo = await db.query.repositories.findFirst({ where: eq(repositories.id, scan.repoId) })

    const date = new Date(scan.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

    const issueRows = reviews
        .flatMap(r => (r.issuesDetected as any[] ?? []).map((i: any) => `| ${r.filePath} | ${i.severity ?? '-'} | ${i.problem ?? '-'} |\n`))
        .join('')

    const md = `# GithubScanner – Engineering Report
**Repository:** ${repo?.fullName ?? 'Unknown'}
**Scan Date:** ${date}
**Scan ID:** ${scanId}

---

## Overall Score: ${Math.round(scan.overallScore ?? 0)}/100

| Category | Score |
|---|---|
| Architecture | ${Math.round(scan.architectureScore ?? 0)} |
| Security | ${Math.round(scan.securityScore ?? 0)} |
| Maintainability | ${Math.round(scan.maintainabilityScore ?? 0)} |
| Scalability | ${Math.round(scan.scalabilityScore ?? 0)} |
| Performance | ${Math.round(scan.performanceScore ?? 0)} |
| Technical Debt Index | ${Math.round(scan.technicalDebtIndex ?? 0)} |

---

## Architecture Summary
${scan.architectureSummary ?? 'N/A'}

## Security Summary
${scan.securitySummary ?? 'N/A'}

## Improvement Summary
${scan.improvementSummary ?? 'N/A'}

---

## File Issues

| File | Severity | Issue |
|---|---|---|
${issueRows || '| — | — | No issues detected |\n'}

---
*Generated by [GithubScanner](${process.env.NEXT_PUBLIC_APP_URL ?? 'https://githubscanner.com'})*
`

    return new NextResponse(md, {
        headers: {
            'Content-Type': 'text/markdown',
            'Content-Disposition': `attachment; filename="githubscanner-report-${scanId}.md"`,
        },
    })
}
